### ISSUE TITLE
Image has string type, instead of Numpy Array

### ISSUE THREAD

**Issue by lasbontechindonesia** [saswat0/License-Plate-Recognition#3]
Hi. I running your code on my comps, and it run well until we encounter one strange error: instead of numpy array, Image has string type. I try to convert it to numpy array with np.fromstring and it gets different error.

Is there any idea how to fix this? Thank you

Error:
Searching for vehicles using YOLO...
	Scanning test_input/image.png
Traceback (most recent call last):
  File "video.py", line 92, in <module>
    R,_ = detect(vehicle_net, vehicle_meta, img_path ,thresh=vehicle_threshold)
  File "/home/lasbonjetson/Documents/License-Plate-Recognition/alpr/darknet/python/darknet.py", line 147, in detect
    im, image = array_to_image(image)
  File "/home/lasbonjetson/Documents/License-Plate-Recognition/alpr/darknet/python/darknet.py", line 18, in array_to_image
    arr = arr.transpose(2, 0, 1)
AttributeError: 'str' object has no attribute 'transpose'.

**Comment by saswat0** [comment]
Hi @lasbontechindonesia 
I'm unable to figure out the bug here. Could you please help me reproduce this error?

**Comment by MingRongXi** [comment]
Hi, I running your code video.py on my machine, this is slow. I want to ask you how many frames are processed in one second on your machine? Thank you！

**Comment by saswat0** [comment]
The fps wont be great unless you have a good GPU for inference
Once you do, set GPU and CUDNN to 1 and compile (make) the darknet source again to allow settings to take effect

**Comment by MingRongXi** [comment]
Thank you！I try it.
