### ISSUE TITLE
How did you make the wpod-net run fast? ?

### ISSUE THREAD

**Issue by MingRongXi** [saswat0/License-Plate-Recognition#5]
Hi, saswat0! I have a 32g PH402 SKU 200 GPU on my friend's machine. It takes hundreds or even thousands of milliseconds for wpod-net to detect the license plate in a frame. It's too slow! How did you make the wpod-net run fast?

**Comment by saswat0** [comment]
Make sure that GPU and CUDNN are set to 1 (in the makefile) before compiling darknet.
I couldn't make it run enough fast. I just skipped a few frames and used kalman filters to reduce the jitter. With a good GPU, the fps is manageable

**Comment by MingRongXi** [comment]
Thank you！I try it again with your method.
