### ISSUE TITLE
what is the opencv version?

### ISSUE THREAD

**Issue by ishamandrekar** [saswat0/License-Plate-Recognition#6]
I am getting errors related to opencv when i run "make".

**Comment by saswat0** [comment]
Please post your error logs

**Comment by mahaveerjain98** [comment]
![image](https://user-images.githubusercontent.com/60811161/113594280-1d20af80-9655-11eb-964b-389618601cf2.png)

While running the demo.py, is there any need for updating opencv or what is the cause.
 i commented the imshow statement and it worked well.

**Comment by saswat0** [comment]
Opencv>=2.4.9 should work fine
Your error seems like an issue with opencv compilation. Run make with opencv as 0 or compile opencv properly before running. I think it causes some issues in windows
