### ISSUE TITLE
How many frames can be processed in one second

### ISSUE THREAD

**Issue by MingRongXi** [saswat0/License-Plate-Recognition#7]
Hi, saswat0! I want to ask you some questions. The program runs slowly on both my CPU and GPU. It takes four seconds to process an image. My cpu is 6 cores and 6 processes, and the memory is 8GB. My GPU is 8GB of TeslaM10. How many frames per second can you process, and what computing environment are you in

**Comment by saswat0** [comment]
Hi @MingRongXi 
Your GPU seems reasonably fine and should provide you with a decent FPS. Please ensure that you build darknet with the cuda and cudnn flags as 1. 
I could get an FPS of 5 on a CPU only system (Intel i7 8th gen) and 12 with a Tesla K80 GPU (colab)

**Comment by MingRongXi** [comment]
Thank you, saswat0. I complied the darknet with the gpu and cudnn flags as 1, so the stage of vehicle-detection and ocr which realized with yolo is very fast. But the wpod-net takes a lot of time, it spends 3s or 4s processing an image.  I run it with the tensorflow-gpu and keras-gpu, which are installed by the command: conda install tensorflow-gpu, conda install keras-gpu. And the speed of GPU and CPU in wpod net is almost the same.

**Comment by saswat0** [comment]
The keras implementation of wpod-net is not memory optimised and hence takes the longest time
You could try skipping frames, running your video source in a separate thread or downgrading the video quality. 
Also, what's your cuda and cudnn version? I worked best with cuda 10.2 and cudnn 7.6.5 in my case

**Comment by MingRongXi** [comment]
My cuda version is 10.2, so I install the cudatoolkit and cudnn with the command: conda install cudatoolkit

**Comment by MingRongXi** [comment]
Sorry, saswat0, I clicked in a wrong place that closed the issue. My cuda version is 10.2, so I install the cudatoolkit and cudnn with the command: conda install cudatoolkit=10.2, conda install cudnn. Because the first command specifies the cudatoolkit version, so the cudnn 7.6.5 is installed. Then I install the tensorflow-gpu with conda install tensorflow-gpu. The tensorflow-gpu 1.8 is installed. But when I run the python video.py, the gpu is not used.
